jectiveList,{objectives}),h('div',{className:'routeList'},segs.map((e,i)=>{const t=treatment(treat,e.id),c=costDisplay(e,t,survey),cls=segmentClass(e,t);return h('div',{className:'segment '+(selSeg===e.id?'selectedSegment':''),key:e.id},h('div',{className:'segmentTop'},h('b',null,`${node(e.a).label} → ${node(e.b).label}`),h('span',null,e.km+' km')),h('small',null,`${knownSegment(e,survey)?e.base:'surface uncertain'} · Class ${cls} · ${c.label}`),phase==='plan'&&h('button',{className:'textButton',onClick:()=>editFrom(i)},'Redraw from '+node(route[i]).label))})))
}
function PeoplePanel({owners,hiddenCount,trust,usedActions,negotiate,commitments,promises}){
 return h('div',null,h('div',{className:'sectionTitle'},h('h3',null,'Access & relationships'),h('small',null,owners.length+' known parties')),hiddenCount>0&&h('div',{className:'warning'},`${hiddenCount} possible ownership interest${hiddenCount===1?' remains':'s remain'} hidden until survey.`),owners.length===0&&h('p',null,'No non-council owner has yet been verified.'),owners.map(o=>{const x=OWNERS[o],ok=trust[o]>=x.threshold;return h('div',{className:'cardlet',key:o},h('div',{className:'stake'},h('div',{className:'avatar',style:{background:ownerColour(o)}},x.name[0]),h('div',null,h('strong',null,x.name),h('small',null,x.role+' · '+o),h('p',null,x.concern))),h('div',{className:'meter'},h('span',{style:{width:trust[o]+'%',background:ok?'#4b8b68':'#b65f42'}})),h('small',null,`Trust ${Math.round(trust[o])}/100 · ${ok?'access agreed':'needs '+x.threshold}`),h('div',{className:'actions'},x.actions.map(a=>{const used=usedActions[o+':'+a.id];return h('button',{className:'tiny',disabled:used,onClick:()=>negotiate(o,a),key:a.id},used?'Used: '+a.label:a.label)})))}),Object.keys(commitments).length>0&&h('div',{className:'cardlet'},h('strong',null,'Binding promises'),Object.keys(commitments).filter(k=>commitments[k]).map(k=>h('div',{className:'promise '+(promises[k]?'met':'miss'),key:k},promises[k]?'✓':'!',k.replace(/([A-Z])/g,' $1').toLowerCase()))))
}
function BuildPanel({selSeg,segs,treat,updateTreatment,fac,toggleFacility,projectCost,projectedCapital,brief,phase,opened,builtTreat,builtFac,survey}){
 const e=segs.find(x=>x.id===selSeg),t=e?treatment(treat,e.id):{};
 const head=h('div',{className:'sectionTitle'},h('h3',null,'Design & construction'),h('small',null,`Next works €${Math.round(projectCost)}k`));
 if(!e)return h('div',null,head,h('div',{className:'metricGrid'},h(Metric,{label:'Projected capital',value:`€${Math.round(projectedCapital)}k`}),h(Metric,{label:'Base envelope',value:`€${brief.budget}k`})),h('p',null,'Select a red route section on the map.'));
 const locked=phase!=='plan';
 const surfaces=h('div',{className:'surfaceGrid'},Object.entries(SURF).map(([k,v])=>h('button',{className:'surface '+((t.surface||'natural')===k?'active':''),disabled:locked,onClick:()=>updateTreatment('surface',k),key:k},h('b',null,v.name),h('small',null,`€${v.rate}k/km · durability ×${v.dur}`))));
 const widths=h('div',{className:'surfaceGrid'},Object.entries(WIDTH).map(([k,v])=>h('button',{className:'surface '+((t.width||'narrow')===k?'active':''),disabled:locked,onClick:()=>updateTreatment('width',k),key:k},h('b',null,v.name),h('small',null,`€${v.rate}k/km · class effect`))));
 const extras=h('div',{className:'actions'},[['drain','Drainage'],['mark','Waymarking'],['gate','Gate/fencing'],['steps','Steps'],['interpret','Interpretation']].map(([k,l])=>h('button',{className:'tiny '+(t[k]?'active':''),disabled:locked,onClick:()=>updateTreatment(k,!t[k]),key:k},l)));
 const facilities=Object.entries(FACILITY_COST).map(([k,c])=>h('button',{className:'tiny '+(fac[k]?'active':''),disabled:locked,onClick:()=>toggleFacility(k),key:k},`${k[0].toUpperCase()+k.slice(1)} · €${c}k`));
 const old=e?treatment(builtTreat,e.id):null,cost=costDisplay(e,t,survey);
 return h('div',null,head,h('div',{className:'metricGrid'},h(Metric,{label:'Projected capital',value:`€${Math.round(projectedCapital)}k`}),h(Metric,{label:'Contingency ceiling',value:`€${Math.round(brief.budget*1.1)}k`})),h('div',{className:'cardlet'},h('strong',null,`${node(e.a).label} → ${node(e.b).label}`),h('p',null,`${e.km} km · Class ${segmentClass(e,t)} · ${cost.known?'verified':'estimated'} ${cost.label}.`),opened&&old&&JSON.stringify(old)!==JSON.stringify(t)&&h('div',{className:'warning'},'This is a retrofit. The original asset remains sunk and removal earns no refund.'),h('h4',null,'Surface'),surfaces,h('h4',null,'Width'),widths,h('h4',null,'Controls and furniture'),extras,h('h3',{style:{marginTop:16}},'Trailhead facilities'),h('div',{className:'actions'},facilities),locked&&h('div',{className:'warning'},'Operations are live. Pause and adapt before changing physical assets.')))
}
function ManagePanel({phase,season,cycleEnd,reputation,political,visitors,incidents,condition,maintain,log,operatingFund,stats,selSeg,closed,toggleClosure,advertisedGrade,setGrade,grade,pauseAndAdapt}){
 const vals=Object.values(condition),conditionAvg=vals.length?avg(vals):100,selectedClosed=selSeg&&closed.has(selSeg);
 return h('div',null,h('div',{className:'sectionTitle'},h('h3',null,'Operations'),h('small',null,phase==='operate'?`${season-(cycleEnd-10)}/10 complete`:'Paused')),h('div',{className:'metricGrid'},h(Metric,{label:'Trail condition',value:Math.round(conditionAvg)+'%'}),h(Metric,{label:'Reputation',value:Math.round(reputation)}),h(Metric,{label:'Total visits',value:visitors.toLocaleString()}),h(Metric,{label:'Incidents',value:incidents}),h(Metric,{label:'Operating fund',value:`€${Math.round(operatingFund)}k`}),h(Metric,{label:'Board support',value:Math.round(political)})),h('label',{className:'fieldLabel'},'Publicly advertised grade',h('select',{value:advertisedGrade,onChange:e=>setGrade(e.target.value)},GRADE_ORDER.map(g=>h('option',{key:g,value:g},g)))),advertisedGrade!==grade&&h('div',{className:'warning'},`Warning: the advertised grade is ${advertisedGrade}, but the physical route is ${grade}.`),phase==='operate'&&h('div',{className:'actions'},h('button',{className:'tiny',onClick:()=>maintain('inspect')},'Inspect · €3k'),h('button',{className:'tiny',onClick:()=>maintain('repair')},'Repair weakest · €18k'),h('button',{className:'tiny',onClick:()=>maintain('drain')},'Clear drains · €6k'),h('button',{className:'tiny',onClick:()=>maintain('workday')},'Community workday · €4k'),operatingFund<10&&h('button',{className:'danger',onClick:()=>maintain('grant')},'Emergency grant +€20k'),selSeg&&h('button',{className:selectedClosed?'primary':'secondary',onClick:()=>toggleClosure(selSeg)},selectedClosed?'Inspect and reopen · €2k':'Close selected section'),h('button',{className:'secondary',onClick:pauseAndAdapt},'Pause and redesign')),h('div',{className:'managementStats'},h('small',null,`Inspections ${stats.inspections} · repairs ${stats.repairs} · drain campaigns ${stats.drains} · preventable incidents ${stats.preventable}`)),h('div',{className:'routeList'},log.map((x,i)=>h('div',{className:'segment',key:i},x))))
}
function MobileInspector({selSeg,segs,condition,closed,toggleClosure,phase,setTab}){
 const e=segs.find(x=>x.id===selSeg);if(!e)return null;
 return h('div',{className:'mobileInspector'},h('div',null,h('strong',null,`${node(e.a).label} → ${node(e.b).label}`),h('small',null,`Condition ${Math.round(condition[e.id]??100)}% · risk ${e.risk}/10`)),h('div',{className:'actions'},h('button',{className:'tiny',onClick:()=>setTab('build')},'Design'),phase==='operate'&&h('button',{className:'tiny',onClick:()=>toggleClosure(e.id)},closed.has(e.id)?'Reopen':'Close')))
}
function EventModal({event,resolveEvent}){
 return h('div',{className:'seasonOverlay'},h('section',{className:'event',role:'dialog','aria-modal':'true','aria-labelledby':'event-title'},h('div',{className:'eyebrow'},'The landscape answers back'),h('h2',{id:'event-title'},event.title),h('p',{className:'lead'},event.text),h('div',{className:'choices'},event.choices.map((c,i)=>h('button',{className:'choice',onClick:()=>resolveEvent(c),key:i},h('strong',null,c.label),h('span',null,`${c.cost>=0?'Cost €'+c.cost+'k':'Funding €'+(-c.cost)+'k'} · reputation ${c.rep>=0?'+':''}${c.rep} · trust ${c.trust>=0?'+':''}${c.trust} · condition ${c.condition>=0?'+':''}${c.condition}`))))))
}

ReactDOM.createRoot(document.getElementById('root')).render(h(App));
