ady?'Open against the brief':opened?'Commit adaptations and reopen':'Open the trail';
 const planActions=phase==='plan'?h('div',{className:'actions planActions'},h('button',{className:'primary',onClick:launch},openLabel),h('button',{className:'secondary',onClick:()=>{if(route.length>1){applyRelationshipPenalty([edge(route[route.length-2],route[route.length-1])]);setRoute(route.slice(0,-1))}},disabled:route.length<2},'Undo last section')):null;
 const accessMessage=hiddenOwners.length?`${hiddenOwners.length} ownership interest${hiddenOwners.length===1?' is':'s are'} still unverified.`:permissions?'Access is agreed for every section.':'Access remains unresolved on part of the route.';
 const sidePanel=h('aside',{className:'side'},h('section',{className:'panel'},h('div',{className:'tabs'},['route','people','build','manage'].map(x=>h('button',{className:'tab '+(tab===x?'active':''),onClick:()=>setTab(x),key:x},x))),panelBody,planActions,h('div',{className:'warning '+(!hiddenOwners.length&&permissions?'good':'')},accessMessage)));
 const mapPanel=h('section',{className:'mapCard'},toolbar,h(MapView,{route,clickNode,survey,overlay,condition,selSeg,setSelSeg,phase,closed}),h(MapLegend,{overlay}),seasonControls,h(MobileInspector,{selSeg,segs,condition,closed,toggleClosure,phase,setTab}));
 return h('div',{className:'app'},h(Top,{capital:brief.budget-projectedCapital,ops:opened?operatingFund:null,weeks,deadline:brief.deadline,season,cycleEnd,phase,political}),h('div',{className:'wrap'},h('div',{className:'workspace'},mapPanel,sidePanel)),event&&h(EventModal,{event,resolveEvent}),toast&&h('div',{className:'toast'},toast));
}

function Top({capital,ops,weeks,deadline,season,cycleEnd,phase,political}){
 return h('header',{className:'topbar'},h('div',{className:'brand'},h('span',{className:'leaf'}),h('div',null,'TRAILCRAFT',h('small',null,'THE LIVING LANDSCAPE'))),h('div',{className:'hud'},h('span',{className:'pill '+(capital<0?'bad':'')},`Capital €${Math.round(capital)}k`),ops!==null&&ops!==undefined&&h('span',{className:'pill '+(ops<0?'bad':'')},`Operations €${Math.round(ops)}k`),h('span',{className:'pill '+(weeks>deadline?'bad':'')},`Week ${weeks}/${deadline}`),political!==undefined&&h('span',{className:'pill'},`Board ${Math.round(political)}`),phase==='operate'&&h('span',{className:'pill'},`Season ${season-(cycleEnd-10)+1}/10`)))
}
function Metric({label,value}){return h('div',{className:'metric'},h('b',null,value),h('small',null,label))}
function LandscapeArt(){return h('div',{className:'heroArt'},h('svg',{viewBox:'0 0 500 300','aria-label':'Stylised Irish landscape with hills, trees and a winding trail',role:'img'},h('path',{d:'M0 230 Q90 180 165 220 T330 195 T500 220 V300 H0Z',fill:'#6f8d65'}),h('path',{d:'M0 265 Q120 205 215 250 T500 235 V300 H0Z',fill:'#d8c66e'}),h('path',{d:'M315 205 L390 80 L470 220Z',fill:'#9fb08c'}),h('path',{d:'M365 135 L390 80 L423 145Z',fill:'#f7f1d8'}),h('path',{d:'M40 270 C120 230 150 250 225 208 S340 180 430 230',fill:'none',stroke:'#f2ecd5',strokeWidth:10,strokeLinecap:'round'}),...Array.from({length:12},(_,i)=>h('g',{key:i,transform:`translate(${20+i*37} ${220-(i%4)*13})`},h('rect',{x:-3,y:10,width:6,height:18,fill:'#3f5d46'}),h('circle',{r:14,fill:'#355a45'}))),h('circle',{cx:80,cy:55,r:25,fill:'#d3a746'}))) }
function MapView({route,clickNode,survey,overlay,condition,selSeg,setSelSeg,phase,closed}){
 const last=route[route.length-1],routeIds=new Set(routeEdges(route).map(e=>e.id));
 return h('div',{className:'map'},h('svg',{viewBox:'0 0 1000 650',preserveAspectRatio:'none',role:'application','aria-label':'Interactive trail planning map'},h('rect',{width:1000,height:650,fill:'#dce5cf'}),h('path',{className:'field',d:'M0 390 L350 330 L510 470 L420 650 L0 650Z'}),h('path',{className:'bog',d:'M40 190 Q210 100 390 240 L330 410 L90 390Z'}),h('path',{className:'forest',d:'M360 120 Q620 30 800 270 L710 470 L420 420Z'}),h('path',{className:'river',d:'M920 610 C780 540 760 430 690 390 S520 500 480 620'}),...[120,180,240,300].map((y,i)=>h('path',{className:'contour',key:i,d:`M350 ${y} Q600 ${y-90} 950 ${y+20}`})),overlay==='ecology'&&h('ellipse',{className:'protected',cx:260,cy:300,rx:170,ry:120}),E.map(e=>{const a=node(e.a),b=node(e.b),on=routeIds.has(e.id),available=phase==='plan'&&(e.a===last||e.b===last);let cls='edge '+(on?'route ':'')+(available?'available ':'')+(closed.has(e.id)?'closed ':'');let style={};if(overlay==='ownership')style.stroke=survey.has(e.a)&&survey.has(e.b)?(a.owner===b.owner?ownerColour(a.owner):'#333'):'#969b8c';if(overlay==='slope')style.stroke=e.risk>8?'#a84b3c':e.risk>5?'#d3a746':'#5c8a62';if(overlay==='condition'&&on)style.stroke=(condition[e.id]??100)<45?'#8d3330':(condition[e.id]??100)<70?'#d3a746':'#4e855d';const select=()=>on&&setSelSeg(e.id);return h('g',{key:e.id},h('line',{className:cls,style,x1:a.x*10,y1:(100-a.y)*6.5,x2:b.x*10,y2:(100-b.y)*6.5}),on&&h('line',{className:'edgeHit',x1:a.x*10,y1:(100-a.y)*6.5,x2:b.x*10,y2:(100-b.y)*6.5,tabIndex:0,role:'button','aria-label':`Select section ${a.label} to ${b.label}`,onClick:select,onKeyDown:e2=>{if(e2.key==='Enter'||e2.key===' '){e2.preventDefault();select()}}}))}),N.map(n=>{const known=survey.has(n.id),isLast=n.id===last,onRoute=route.includes(n.id);let fill;if(overlay==='ownership')fill=known?ownerColour(n.owner):'#eee8cf';else if(overlay==='ecology')fill=known?(n.risk>=8?'#b65f42':'#fff8de'):'#eee8cf';else if(overlay==='slope')fill=known?(n.slope>=8?'#9f4137':n.slope>=5?'#d3a746':'#7aa273'):'#eee8cf';const activate=()=>clickNode(n.id);return h('g',{className:'node '+(isLast?'selected ':'')+(onRoute?'onRoute':''),key:n.id,transform:`translate(${n.x*10} ${(100-n.y)*6.5})`,tabIndex:0,role:'button','aria-label':`${n.label}${known?`, ${n.terrain}, ${n.owner}, risk ${n.risk} of 10`:', not surveyed'}`,onClick:activate,onKeyDown:e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}}},h('circle',{className:'nodeHit',r:23}),h('circle',{r:isLast?13:10,style:{fill}}),h('text',{x:14,y:-11},n.label),known&&h('text',{className:'nodeMeta',x:14,y:8},`${n.owner} · risk ${n.risk}/10`))})))
}
function MapLegend({overlay}){
 const items=overlay==='ownership'?Object.entries(OWNER_COLOURS).map(([k,v])=>[v,k]):overlay==='slope'?[['#5c8a62','Gentle'],['#d3a746','Steep'],['#a84b3c','Very steep']]:overlay==='condition'?[['#4e855d','Good'],['#d3a746','Worn'],['#8d3330','Poor']]:overlay==='ecology'?[['#b65f42','Sensitive ground'],['#eee8cf','Not surveyed']]:[['#d15c39','Current route'],['#6e795e','Available link'],['#5e9db0','River']];
 return h('div',{className:'legend','aria-label':'Map legend'},items.map(([c,l])=>h('span',{key:l},h('i',{style:{background:c}}),l)),h('span',null,h('i',{className:'dash'}),'Closed section'))
}
function ObjectiveList({objectives}){return h('div',{className:'objectives'},objectives.map(o=>h('div',{className:'objective '+(o.met?'met':'miss'),key:o.id},h('span',{className:'objectiveIcon'},o.met?'✓':'!'),h('span',null,o.label),o.hard&&h('small',null,'required'))))}
function RoutePanel({route,segs,length,grade,loop,survey,surveyNode,surveyRoute,phase,objectives,editFrom,advertisedGrade,setGrade,selSeg,treat}){
 const last=node(route[route.length-1]);
 return h('div',null,h('div',{className:'sectionTitle'},h('h3',null,'Route desk'),h('small',null,`${segs.length} sections`)),h('div',{className:'metricGrid'},h(Metric,{label:'Length',value:length.toFixed(1)+' km'}),h(Metric,{label:'Physical grade',value:grade})),h('label',{className:'fieldLabel'},'Advertised grade',h('select',{value:advertisedGrade,onChange:e=>setGrade(e.target.value)},GRADE_ORDER.map(g=>h('option',{key:g,value:g},g)))),phase==='plan'&&last&&h('div',{className:'cardlet'},h('strong',null,last.label),h('p',null,survey.has(last.id)?`${last.terrain}, ${last.owner}. Elevation ${last.elev} m. Ground risk ${last.risk}/10.`:'Ground, ownership and construction costs are still uncertain.'),h('div',{className:'actions'},h('button',{className:'tiny',disabled:survey.has(last.id),onClick:()=>surveyNode(last.id)},survey.has(last.id)?'Survey complete':'Survey this point · €2k / 1 week'),h('button',{className:'tiny',onClick:surveyRoute},'Survey whole route'))),h('div',{className:'warning '+(loop?'good':'')},loop?'The route returns to its starting point.':'The route does not yet return to its trailhead.'),h(Ob